# Generated by Django 4.0 on 2022-02-02 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Foodapp', '0003_bill_customer_orderhistory'),
        ('Foodapp', '0004_orderhistory_delete_ordershistory'),
    ]

    operations = [
    ]
