# Generated by Django 4.0 on 2022-02-02 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Foodapp', '0006_alter_bill_table_alter_category_table_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='bill',
            table=None,
        ),
        migrations.AlterModelTable(
            name='category',
            table=None,
        ),
        migrations.AlterModelTable(
            name='customer',
            table=None,
        ),
        migrations.AlterModelTable(
            name='item',
            table=None,
        ),
        migrations.AlterModelTable(
            name='orderhistory',
            table=None,
        ),
    ]
