const menu = [
  {
    id: "1",
    title: "buttermilk pancakes",
    category: "breakfast",
    price: 120,
    desc: "I'm baby woke mlkshk wolf bitters live-edge blue bottle, hammock freegan copper mug whatever cold-pressed ",
  },
  {
    id: "2",
    title: "diner double",
    category: "lunch",
    price: 250,
    desc: "vaporware iPhone mumblecore selvage raw denim slow-carb leggings gochujang helvetica man braid jianbing. Marfa thundercats ",
  },
  {
    id: "3",
    title: "godzilla milkshake",
    category: "shakes",
    price: 60,
    desc: "ombucha chillwave fanny pack 3 wolf moon street art photo booth before they sold out organic viral.",
  },
  {
    id: "4",
    title: "country delight",
    category: "breakfast",
    price: 80,
    desc: "Shabby chic keffiyeh neutra snackwave pork belly shoreditch. Prism austin mlkshk truffaut, ",
  },
  {
    id: "5",
    title: "egg attack",
    category: "lunch",
    price: 200,
    desc: "franzen vegan pabst bicycle rights kickstarter pinterest meditation farm-to-table 90's pop-up ",
  },
  {
    id: "6",
    title: "oreo dream",
    category: "shakes",
    price: 90,
    desc: "Portland chicharrones ethical edison bulb, palo santo craft beer chia heirloom iPhone everyday",
  },
  {
    id: "7",
    title: "bacon overflow",
    category: "breakfast",
    price: 100,
    desc: "carry jianbing normcore freegan. Viral single-origin coffee live-edge, pork belly cloud bread iceland put a bird ",
  },
  {
    id: "8",
    title: "american classic",
    category: "lunch",
    price: 160,
    desc: "on it tumblr kickstarter thundercats migas everyday carry squid palo santo leggings. Food truck truffaut  ",
  },
  {
    id: "9",
    title: "quarantine buddy",
    category: "shakes",
    price: 70,
    desc: "skateboard fam synth authentic semiotics. Live-edge lyft af, edison bulb yuccie crucifix microdosing.",
  },
  {
    id: "10",
    title: "Paneer Tikka",
    category: "starter",
    price: 120,
    desc: "Spicy Paneer or chilli paneer or cottage cheese, served in black Dish with capsicum and onion",
  },
  {
    id: "11",
    title: "Chilli Chicken",
    category: "starter",
    price: 150,
    desc: "Chilli chicken is a popular Indo-Chinese dish of chicken of Hakka Chinese heritage",
  },
  {
    id: "12",
    title: "Fish Pakora",
    category: "starter",
    price: 180,
    desc: "Most people are fish lovers, and having fish pakora at the party can also convince a hesitant guest to taste something new, and a deep-fried crunchy pakora dipped with chutney can be zesty.",
  },
  {
    id: "13",
    title: "Chicken Manchurian",
    category: "starter",
    price: 150,
    desc: "It is fusion food with Chinese cuisine adapted with some tangy soya sauce to bring out something new. ",
  },
  {
    id: "14",
    title: "Sweet Potato Tikki",
    category: "starter",
    price: 120,
    desc: "Crispy outside, creamy inside, and lightly spiced, these roasted sweet potato wedges make for a healthy appetizer",
  },
];
export default menu;

